name: MoneyPrinterTurbo
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda-nvrtc=12.9.41=h5888daf_0
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.0.56=hcd2ec93_1
  - debugpy=1.8.14=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.9.0.13=h9ab20c4_0
  - libcudnn=9.10.0.56=h4840ae0_1
  - libcudnn-dev=9.10.0.56=hcd2ec93_1
  - libedit=3.1.20230828=h5eee18b_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.0=h7b32b05_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311h9ecbd09_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.11.8=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.11=7_cp311
  - pyzmq=26.4.0=py311h7deb3e3_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.2=h2c6b66d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - alembic==1.16.4
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asteroid-filterbanks==0.4.0
      - attrs==25.3.0
      - audioread==3.0.1
      - av==15.0.0
      - blinker==1.9.0
      - brotli==1.1.0
      - cachetools==6.1.0
      - certifi==2025.7.14
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.2
      - chatterbox-tts==0.1.2
      - click==8.2.1
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - conformer==0.3.2
      - contourpy==1.3.2
      - ctranslate2==4.4.0
      - cycler==0.12.1
      - diffusers==0.29.0
      - distlib==0.4.0
      - distro==1.9.0
      - docopt==0.6.2
      - edge-tts==7.0.2
      - einops==0.8.1
      - faster-whisper==1.1.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - g4f==0.5.7.5
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.2.3
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.4
      - humanfriendly==10.0
      - hyperpyyaml==1.2.2
      - identify==2.6.12
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - julius==0.2.7
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - loguru==0.7.3
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - narwhals==1.47.1
      - networkx==3.5
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnx==1.18.0
      - onnxruntime==1.22.1
      - openai==1.97.0
      - optuna==4.4.0
      - pandas==2.3.1
      - pillow==11.3.0
      - pooch==1.8.2
      - pre-commit==4.2.0
      - primepy==1.3
      - proglog==0.1.12
      - propcache==0.3.2
      - protobuf==6.31.1
      - pyannote-audio==3.3.2
      - pyannote-core==5.0.0
      - pyannote-database==5.1.3
      - pyannote-metrics==3.2.1
      - pyannote-pipeline==3.0.1
      - pyarrow==21.0.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - pytorch-lightning==2.5.2
      - pytorch-metric-learning==2.8.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - resemble-perth==1.0.1
      - rich==14.0.0
      - rpds-py==0.26.0
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - s3tokenizer==0.2.0
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.16.0
      - semver==3.0.4
      - sentence-transformers==5.0.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - speechbrain==1.0.3
      - sqlalchemy==2.0.41
      - srt==3.5.3
      - streamlit==1.47.0
      - sympy>=1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tokenizers==0.20.1
      - toml==0.10.2
      - torch==2.6.0
      - torch-audiomentations==0.12.0
      - torch-pitch-shift==1.2.5
      - torchaudio==2.6.0
      - torchmetrics==1.7.4
      - torchvision==0.21.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton>=3.1.0
      - typer==0.16.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - virtualenv==20.31.2
      - watchdog==6.0.0
      - whisper==1.1.10
      - whisperx==3.3.1
      - flickrapi>=2.4.0
prefix: /home/asad/miniconda3/envs/MoneyPrinterTurbo
